// SPDX-License-Identifier: LGPL-2.1-or-later
// Translated from VapourSynth R76, commit aa7e83a0aaf87477b5e0fc13c5b97c5aa15a06b7.
// Copyright (c) 2012-2026 Fredrik Mellbin. See LICENSE and tests/headers/.
package vapoursynth

import "core:c"

// Table order is part of the C ABI. Access through the pointer provided by the core.
VSPLUGINAPI :: struct {
	getAPIVersion: proc "system" () -> c.int,
	configPlugin: proc "system" (
		identifier: cstring,
		pluginNamespace: cstring,
		name: cstring,
		pluginVersion: c.int,
		apiVersion: c.int,
		flags: c.int,
		plugin: ^VSPlugin,
	) -> c.int,
	registerFunction: proc "system" (
		name: cstring,
		args: cstring,
		returnType: cstring,
		argsFunc: VSPublicFunction,
		functionData: rawptr,
		plugin: ^VSPlugin,
	) -> c.int,
}

// Borrowed, read-only table. C const qualifiers are not enforced by Odin:
// info/format pointers, getReadPtr, and getFramePropertiesRO remain read-only.
VSAPI :: struct {
	// Audio and video filter related including nodes
	createVideoFilter: proc "system" (
		out: ^VSMap,
		name: cstring,
		vi: ^VSVideoInfo,
		getFrame: VSFilterGetFrame,
		free: VSFilterFree,
		filterMode: c.int,
		dependencies: [^]VSFilterDependency,
		numDeps: c.int,
		instanceData: rawptr,
		core: ^VSCore,
	),
	createVideoFilter2: proc "system" (
		name: cstring,
		vi: ^VSVideoInfo,
		getFrame: VSFilterGetFrame,
		free: VSFilterFree,
		filterMode: c.int,
		dependencies: [^]VSFilterDependency,
		numDeps: c.int,
		instanceData: rawptr,
		core: ^VSCore,
	) -> ^VSNode,
	createAudioFilter: proc "system" (
		out: ^VSMap,
		name: cstring,
		ai: ^VSAudioInfo,
		getFrame: VSFilterGetFrame,
		free: VSFilterFree,
		filterMode: c.int,
		dependencies: [^]VSFilterDependency,
		numDeps: c.int,
		instanceData: rawptr,
		core: ^VSCore,
	),
	createAudioFilter2: proc "system" (
		name: cstring,
		ai: ^VSAudioInfo,
		getFrame: VSFilterGetFrame,
		free: VSFilterFree,
		filterMode: c.int,
		dependencies: [^]VSFilterDependency,
		numDeps: c.int,
		instanceData: rawptr,
		core: ^VSCore,
	) -> ^VSNode,
	setLinearFilter: proc "system" (node: ^VSNode) -> c.int,
	setCacheMode: proc "system" (node: ^VSNode, mode: c.int),
	setCacheOptions: proc "system" (node: ^VSNode, fixedSize: c.int, maxSize: c.int, maxHistorySize: c.int),
	freeNode: proc "system" (node: ^VSNode),
	addNodeRef: proc "system" (node: ^VSNode) -> ^VSNode,
	getNodeType: proc "system" (node: ^VSNode) -> c.int,
	getVideoInfo: proc "system" (node: ^VSNode) -> ^VSVideoInfo,
	getAudioInfo: proc "system" (node: ^VSNode) -> ^VSAudioInfo,
	// Frame related functions
	newVideoFrame: proc "system" (
		format: ^VSVideoFormat,
		width: c.int,
		height: c.int,
		propSrc: ^VSFrame,
		core: ^VSCore,
	) -> ^VSFrame,
	newVideoFrame2: proc "system" (
		format: ^VSVideoFormat,
		width: c.int,
		height: c.int,
		planeSrc: [^]^VSFrame,
		planes: [^]c.int,
		propSrc: ^VSFrame,
		core: ^VSCore,
	) -> ^VSFrame,
	newAudioFrame: proc "system" (
		format: ^VSAudioFormat,
		numSamples: c.int,
		propSrc: ^VSFrame,
		core: ^VSCore,
	) -> ^VSFrame,
	newAudioFrame2: proc "system" (
		format: ^VSAudioFormat,
		numSamples: c.int,
		channelSrc: [^]^VSFrame,
		channels: [^]c.int,
		propSrc: ^VSFrame,
		core: ^VSCore,
	) -> ^VSFrame,
	freeFrame: proc "system" (f: ^VSFrame),
	addFrameRef: proc "system" (f: ^VSFrame) -> ^VSFrame,
	copyFrame: proc "system" (f: ^VSFrame, core: ^VSCore) -> ^VSFrame,
	getFramePropertiesRO: proc "system" (f: ^VSFrame) -> ^VSMap,
	getFramePropertiesRW: proc "system" (f: ^VSFrame) -> ^VSMap,
	getStride: proc "system" (f: ^VSFrame, plane: c.int) -> c.ptrdiff_t,
	getReadPtr: proc "system" (f: ^VSFrame, plane: c.int) -> [^]u8,
	// Invalidates previously acquired read pointers to this frame.
	getWritePtr: proc "system" (f: ^VSFrame, plane: c.int) -> [^]u8,
	getVideoFrameFormat: proc "system" (f: ^VSFrame) -> ^VSVideoFormat,
	getAudioFrameFormat: proc "system" (f: ^VSFrame) -> ^VSAudioFormat,
	getFrameType: proc "system" (f: ^VSFrame) -> c.int,
	getFrameWidth: proc "system" (f: ^VSFrame, plane: c.int) -> c.int,
	getFrameHeight: proc "system" (f: ^VSFrame, plane: c.int) -> c.int,
	getFrameLength: proc "system" (f: ^VSFrame) -> c.int,
	// General format functions
	// Both name functions require a buffer of at least 32 bytes, including the terminator.
	getVideoFormatName: proc "system" (format: ^VSVideoFormat, buffer: [^]u8) -> c.int,
	getAudioFormatName: proc "system" (format: ^VSAudioFormat, buffer: [^]u8) -> c.int,
	queryVideoFormat: proc "system" (
		format: ^VSVideoFormat,
		colorFamily: c.int,
		sampleType: c.int,
		bitsPerSample: c.int,
		subSamplingW: c.int,
		subSamplingH: c.int,
		core: ^VSCore,
	) -> c.int,
	queryAudioFormat: proc "system" (
		format: ^VSAudioFormat,
		sampleType: c.int,
		bitsPerSample: c.int,
		channelLayout: u64,
		core: ^VSCore,
	) -> c.int,
	queryVideoFormatID: proc "system" (
		colorFamily: c.int,
		sampleType: c.int,
		bitsPerSample: c.int,
		subSamplingW: c.int,
		subSamplingH: c.int,
		core: ^VSCore,
	) -> u32,
	getVideoFormatByID: proc "system" (format: ^VSVideoFormat, id: u32, core: ^VSCore) -> c.int,
	// Frame request and filter getframe functions
	// getFrame/getFrameAsync are for hosts or filter constructors, never filter get-frame callbacks.
	getFrame: proc "system" (n: c.int, node: ^VSNode, errorMsg: [^]u8, bufSize: c.int) -> ^VSFrame,
	getFrameAsync: proc "system" (n: c.int, node: ^VSNode, callback: VSFrameDoneCallback, userData: rawptr),
	getFrameFilter: proc "system" (n: c.int, node: ^VSNode, frameCtx: ^VSFrameContext) -> ^VSFrame,
	requestFrameFilter: proc "system" (n: c.int, node: ^VSNode, frameCtx: ^VSFrameContext),
	releaseFrameEarly: proc "system" (node: ^VSNode, n: c.int, frameCtx: ^VSFrameContext),
	cacheFrame: proc "system" (frame: ^VSFrame, n: c.int, frameCtx: ^VSFrameContext),
	setFilterError: proc "system" (errorMessage: cstring, frameCtx: ^VSFrameContext),
	// External functions
	createFunction: proc "system" (
		func: VSPublicFunction,
		userData: rawptr,
		free: VSFreeFunctionData,
		core: ^VSCore,
	) -> ^VSFunction,
	freeFunction: proc "system" (f: ^VSFunction),
	addFunctionRef: proc "system" (f: ^VSFunction) -> ^VSFunction,
	callFunction: proc "system" (func: ^VSFunction, in_: ^VSMap, out: ^VSMap),
	// Map and property access functions
	createMap: proc "system" () -> ^VSMap,
	freeMap: proc "system" (map_: ^VSMap),
	clearMap: proc "system" (map_: ^VSMap),
	copyMap: proc "system" (src: ^VSMap, dst: ^VSMap),
	mapSetError: proc "system" (map_: ^VSMap, errorMessage: cstring),
	mapGetError: proc "system" (map_: ^VSMap) -> cstring,
	mapNumKeys: proc "system" (map_: ^VSMap) -> c.int,
	mapGetKey: proc "system" (map_: ^VSMap, index: c.int) -> cstring,
	mapDeleteKey: proc "system" (map_: ^VSMap, key: cstring) -> c.int,
	mapNumElements: proc "system" (map_: ^VSMap, key: cstring) -> c.int,
	mapGetType: proc "system" (map_: ^VSMap, key: cstring) -> c.int,
	mapSetEmpty: proc "system" (map_: ^VSMap, key: cstring, type_: c.int) -> c.int,
	mapGetInt: proc "system" (map_: ^VSMap, key: cstring, index: c.int, error: ^c.int) -> i64,
	mapGetIntSaturated: proc "system" (map_: ^VSMap, key: cstring, index: c.int, error: ^c.int) -> c.int,
	mapGetIntArray: proc "system" (map_: ^VSMap, key: cstring, error: ^c.int) -> [^]i64,
	mapSetInt: proc "system" (map_: ^VSMap, key: cstring, i: i64, append: c.int) -> c.int,
	mapSetIntArray: proc "system" (map_: ^VSMap, key: cstring, i: [^]i64, size: c.int) -> c.int,
	mapGetFloat: proc "system" (map_: ^VSMap, key: cstring, index: c.int, error: ^c.int) -> f64,
	mapGetFloatSaturated: proc "system" (map_: ^VSMap, key: cstring, index: c.int, error: ^c.int) -> f32,
	mapGetFloatArray: proc "system" (map_: ^VSMap, key: cstring, error: ^c.int) -> [^]f64,
	mapSetFloat: proc "system" (map_: ^VSMap, key: cstring, d: f64, append: c.int) -> c.int,
	mapSetFloatArray: proc "system" (map_: ^VSMap, key: cstring, d: [^]f64, size: c.int) -> c.int,
	mapGetData: proc "system" (map_: ^VSMap, key: cstring, index: c.int, error: ^c.int) -> cstring,
	mapGetDataSize: proc "system" (map_: ^VSMap, key: cstring, index: c.int, error: ^c.int) -> c.int,
	mapGetDataTypeHint: proc "system" (map_: ^VSMap, key: cstring, index: c.int, error: ^c.int) -> c.int,
	mapSetData: proc "system" (
		map_: ^VSMap,
		key: cstring,
		data: cstring,
		size: c.int,
		type_: c.int,
		append: c.int,
	) -> c.int,
	mapGetNode: proc "system" (map_: ^VSMap, key: cstring, index: c.int, error: ^c.int) -> ^VSNode,
	mapSetNode: proc "system" (map_: ^VSMap, key: cstring, node: ^VSNode, append: c.int) -> c.int,
	// Consumes node even on failure; the caller must not release it afterward.
	mapConsumeNode: proc "system" (map_: ^VSMap, key: cstring, node: ^VSNode, append: c.int) -> c.int,
	mapGetFrame: proc "system" (map_: ^VSMap, key: cstring, index: c.int, error: ^c.int) -> ^VSFrame,
	mapSetFrame: proc "system" (map_: ^VSMap, key: cstring, f: ^VSFrame, append: c.int) -> c.int,
	// Consumes f even on failure; the caller must not release it afterward.
	mapConsumeFrame: proc "system" (map_: ^VSMap, key: cstring, f: ^VSFrame, append: c.int) -> c.int,
	mapGetFunction: proc "system" (map_: ^VSMap, key: cstring, index: c.int, error: ^c.int) -> ^VSFunction,
	mapSetFunction: proc "system" (map_: ^VSMap, key: cstring, func: ^VSFunction, append: c.int) -> c.int,
	// Consumes func even on failure; the caller must not release it afterward.
	mapConsumeFunction: proc "system" (map_: ^VSMap, key: cstring, func: ^VSFunction, append: c.int) -> c.int,
	// Plugin and plugin function related
	registerFunction: proc "system" (
		name: cstring,
		args: cstring,
		returnType: cstring,
		argsFunc: VSPublicFunction,
		functionData: rawptr,
		plugin: ^VSPlugin,
	) -> c.int,
	getPluginByID: proc "system" (identifier: cstring, core: ^VSCore) -> ^VSPlugin,
	getPluginByNamespace: proc "system" (ns: cstring, core: ^VSCore) -> ^VSPlugin,
	getNextPlugin: proc "system" (plugin: ^VSPlugin, core: ^VSCore) -> ^VSPlugin,
	getPluginName: proc "system" (plugin: ^VSPlugin) -> cstring,
	getPluginID: proc "system" (plugin: ^VSPlugin) -> cstring,
	getPluginNamespace: proc "system" (plugin: ^VSPlugin) -> cstring,
	getNextPluginFunction: proc "system" (func: ^VSPluginFunction, plugin: ^VSPlugin) -> ^VSPluginFunction,
	getPluginFunctionByName: proc "system" (name: cstring, plugin: ^VSPlugin) -> ^VSPluginFunction,
	getPluginFunctionName: proc "system" (func: ^VSPluginFunction) -> cstring,
	getPluginFunctionArguments: proc "system" (func: ^VSPluginFunction) -> cstring,
	getPluginFunctionReturnType: proc "system" (func: ^VSPluginFunction) -> cstring,
	getPluginPath: proc "system" (plugin: ^VSPlugin) -> cstring,
	getPluginVersion: proc "system" (plugin: ^VSPlugin) -> c.int,
	invoke: proc "system" (plugin: ^VSPlugin, name: cstring, args: ^VSMap) -> ^VSMap,
	// Core and information
	createCore: proc "system" (flags: c.int) -> ^VSCore,
	freeCore: proc "system" (core: ^VSCore),
	setMaxCacheSize: proc "system" (bytes: i64, core: ^VSCore) -> i64,
	setThreadCount: proc "system" (threads: c.int, core: ^VSCore) -> c.int,
	getCoreInfo: proc "system" (core: ^VSCore, info: ^VSCoreInfo),
	getAPIVersion: proc "system" () -> c.int,
	// Message handler
	logMessage: proc "system" (msgType: c.int, msg: cstring, core: ^VSCore),
	addLogHandler: proc "system" (
		handler: VSLogHandler,
		free: VSLogHandlerFree,
		userData: rawptr,
		core: ^VSCore,
	) -> ^VSLogHandle,
	removeLogHandler: proc "system" (handle: ^VSLogHandle, core: ^VSCore) -> c.int,
	// Added in API 4.1, mostly graph and node inspection, PLEASE DON'T USE INSIDE FILTERS
	// Additional cache management to free memory
	clearNodeCache: proc "system" (node: ^VSNode),
	clearCoreCaches: proc "system" (core: ^VSCore),
	// Basic node information
	getNodeName: proc "system" (node: ^VSNode) -> cstring,
	getNodeFilterMode: proc "system" (node: ^VSNode) -> c.int,
	getNumNodeDependencies: proc "system" (node: ^VSNode) -> c.int,
	getNodeDependency: proc "system" (node: ^VSNode, index: c.int) -> ^VSFilterDependency,
	// Node timing functions
	getCoreNodeTiming: proc "system" (core: ^VSCore) -> c.int,
	setCoreNodeTiming: proc "system" (core: ^VSCore, enable: c.int),
	getNodeProcessingTime: proc "system" (node: ^VSNode, reset: c.int) -> i64,
	getFreedNodeProcessingTime: proc "system" (core: ^VSCore, reset: c.int) -> i64,
	// Added in API 4.2
	getCoreInfo2: proc "system" (core: ^VSCore, info: ^VSCoreInfo2),
}

// Experimental graph extension. Requires an exact runtime API version match,
// ccfEnableGraphInspection, and no concurrent frame requests or API calls.
// Cast a ^VSAPI to ^VSGraphAPI only after checking those conditions.
VSGraphAPI :: struct {
	using api: VSAPI,
	getNodeCreationFunctionName: proc "system" (node: ^VSNode, level: c.int) -> cstring,
	getNodeCreationPluginID: proc "system" (node: ^VSNode, level: c.int) -> cstring,
	getNodeCreationPluginNS: proc "system" (node: ^VSNode, level: c.int) -> cstring,
	getNodeCreationFunctionArguments: proc "system" (node: ^VSNode, level: c.int) -> ^VSMap,
}
