[project]
name = "vapoursynth-odin-easy-host"
version = "0.1.0"
description = "Standalone Odin VapourSynth easy host host"
readme = "README.md"
requires-python = ">=3.14"
license = "LGPL-2.1-or-later"
license-files = ["LICENSE", "THIRD_PARTY_LICENSES.md"]
dependencies = ["vapoursynth>=76,<80"]

[tool.uv]
package = false

[tool.odin]
name = "easy_host"
kind = "host"
stb = false

[tool.odin.bindings]
repository = "PlaneSight/vapoursynth-odin"
revision = "e2e850dac151b63f3856665f42943f1fb4bfdd11"
sha256 = "bf290f75df999b5336024c63a62af6857fff2b686ccd0b77b6a3d05fcc45061f"
